//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDesingApp.databases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDatabasesEntities : DbContext
    {
        public TestDatabasesEntities()
            : base("name=TestDatabasesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Деятельность> Деятельность { get; set; }
        public virtual DbSet<ДеятельностьСотрудник> ДеятельностьСотрудник { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<УчётнаяЗапись> УчётнаяЗапись { get; set; }
    }
}
