//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDesingApp.databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Деятельность
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Деятельность()
        {
            this.ДеятельностьСотрудник = new HashSet<ДеятельностьСотрудник>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public string Описание { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ДеятельностьСотрудник> ДеятельностьСотрудник { get; set; }
    }
}
