//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDesingApp.databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДеятельностьСотрудник
    {
        public int КодСорудника { get; set; }
        public int КодДеятельности { get; set; }
        public System.DateTime НачалоПериода { get; set; }
        public System.DateTime КонецПериода { get; set; }
    
        public virtual Деятельность Деятельность { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
