//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDesingApp.databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Аккаунт = new HashSet<Аккаунт>();
        }
    
        public int Код { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public Nullable<bool> Пол { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public string АдресПроживание { get; set; }
        public string Телефон { get; set; }
        public string ИНН { get; set; }
        public string ОМС { get; set; }
        public string СНИЛС { get; set; }
        public Nullable<bool> СемейноеПоложение { get; set; }
        public Nullable<System.DateTime> ДатаТрудоустройства { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Аккаунт> Аккаунт { get; set; }
    }
}
