//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDesingApp.databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class УчётнаяЗапись
    {
        public int Код { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int Доступ { get; set; }
        public int КодСотрудника { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
